apiVersion: v2
name: simplebank
description: A Helm chart for the Simple Bank API
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: postgresql
    version: 12.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled